language: minimal
sudo: false

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libsdl2-dev
    - libsdl2-ttf-dev
    - ocl-icd-libopencl1
    - opencl-headers

before_install:
 # install Futhark
 - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
 - tar xf futhark-nightly-linux-x86_64.tar.xz
 - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

install:
  - futhark pkg sync

script:
  - futhark test --no-terminal lib
  - make
  - futhark pkg upgrade
  - futhark pkg sync
  - futhark test --no-terminal lib
  - make
